import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult, MarketContext, Quote } from "./types";
import { formatQuarter, type RoadmapItem, BUCKET_META, type Bucket } from "./roadmap";

function quoteText(q: Quote): string {
  return typeof q === "string" ? q : q.text;
}
function quoteAttr(q: Quote): string {
  if (typeof q === "string") return "";
  const parts = [q.source, q.context, q.date].filter(Boolean);
  return parts.join(" · ");
}
function safeName(s: string): string {
  return (s || "untitled").replace(/[^a-z0-9-_]+/gi, "-").toLowerCase();
}
function today(): string {
  return new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

const MARGIN = 14;
const PAGE_WIDTH = 210; // A4 mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function header(doc: jsPDF, productName: string, subtitle: string) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(20);
  doc.text(productName || "Untitled", MARGIN, 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`${subtitle} · ${today()} · Generated by InsightFlow`, MARGIN, 26);
  doc.setDrawColor(220);
  doc.line(MARGIN, 30, PAGE_WIDTH - MARGIN, 30);
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(20);
  doc.text(text, MARGIN, y);
  return y + 6;
}

function paragraph(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
  doc.text(lines, MARGIN, y);
  return y + lines.length * 5 + 2;
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 285) {
    doc.addPage();
    return 20;
  }
  return y;
}

function getY(doc: jsPDF & { lastAutoTable?: { finalY: number } }): number {
  return (doc.lastAutoTable?.finalY ?? 30) + 8;
}

export function exportAnalysisPdf(
  result: AnalysisResult,
  productName: string,
  market: MarketContext | null,
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" }) as jsPDF & {
    lastAutoTable?: { finalY: number };
  };
  header(doc, productName, "Feedback analysis");

  // KPIs
  autoTable(doc, {
    startY: 36,
    head: [["Reviews analyzed", "Overall sentiment", "Critical issues", "Top pain area"]],
    body: [[
      String(result.reviewsAnalyzed),
      result.overallSentiment,
      String(result.criticalIssuesCount),
      result.topPainArea,
    ]],
    theme: "grid",
    headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 10, textColor: 30 },
    margin: { left: MARGIN, right: MARGIN },
  });

  // Executive summary
  let y = getY(doc);
  y = ensureSpace(doc, y, 30);
  y = sectionTitle(doc, "Executive summary", y);
  y = paragraph(doc, result.executiveSummary, y);

  // Issues table
  y = ensureSpace(doc, y + 4, 30);
  y = sectionTitle(doc, "Prioritized pain points", y);
  autoTable(doc, {
    startY: y,
    head: [["#", "Title", "Priority", "Category", "Impact", "Mentions"]],
    body: result.issues.map((it, i) => [
      i + 1,
      it.title,
      it.priority,
      it.category,
      it.impactScore,
      it.mentions,
    ]),
    theme: "striped",
    headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 70 },
      2: { cellWidth: 16 },
      3: { cellWidth: 32 },
      4: { cellWidth: 16 },
      5: { cellWidth: 18 },
    },
    margin: { left: MARGIN, right: MARGIN },
  });

  // Issue descriptions
  y = getY(doc);
  for (const [i, it] of result.issues.entries()) {
    y = ensureSpace(doc, y, 20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(20);
    doc.text(`${i + 1}. ${it.title}`, MARGIN, y);
    y += 5;
    y = paragraph(doc, it.description, y);
    y += 2;
  }

  // Market context
  if (market) {
    y = ensureSpace(doc, y + 4, 30);
    y = sectionTitle(doc, "Market context", y);
    if (market.verdict) {
      y = paragraph(
        doc,
        `Verdict — ${market.verdict.label}: ${market.verdict.rationale}`,
        y,
      );
    }
    if (market.marketSize?.statement) {
      y = paragraph(doc, `Market size: ${market.marketSize.statement}`, y);
    }
    if (market.trends?.length) {
      y = ensureSpace(doc, y + 2, 20);
      y = sectionTitle(doc, "Trends", y);
      autoTable(doc, {
        startY: y,
        head: [["Statement", "Direction", "Source"]],
        body: market.trends.map((t) => [t.statement, t.direction, t.source]),
        theme: "striped",
        headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        margin: { left: MARGIN, right: MARGIN },
      });
      y = getY(doc);
    }
    if (market.competitors?.length) {
      y = ensureSpace(doc, y + 2, 20);
      y = sectionTitle(doc, "Competitors", y);
      autoTable(doc, {
        startY: y,
        head: [["Name", "Approach", "Signal"]],
        body: market.competitors.map((c) => [c.name, c.approach, c.signal]),
        theme: "striped",
        headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        margin: { left: MARGIN, right: MARGIN },
      });
      y = getY(doc);
    }
    if (market.news?.length) {
      y = ensureSpace(doc, y + 2, 20);
      y = sectionTitle(doc, "Recent news", y);
      autoTable(doc, {
        startY: y,
        head: [["Headline", "Summary", "Source", "Date"]],
        body: market.news.map((n) => [n.headline, n.summary, n.source, n.date]),
        theme: "striped",
        headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
        bodyStyles: { fontSize: 8 },
        margin: { left: MARGIN, right: MARGIN },
      });
      y = getY(doc);
    }
  }

  // Recommendations
  if (result.recommendations?.length) {
    y = ensureSpace(doc, y + 4, 20);
    y = sectionTitle(doc, "Top recommendations", y);
    for (const [i, rec] of result.recommendations.entries()) {
      y = ensureSpace(doc, y, 14);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(20);
      doc.text(`${i + 1}. ${rec.title}`, MARGIN, y);
      y += 5;
      y = paragraph(doc, rec.detail, y);
    }
  }

  // Comments appendix
  doc.addPage();
  let cy = 20;
  cy = sectionTitle(doc, "Appendix — Comments & evidence", cy);
  cy = paragraph(
    doc,
    "Verbatim user feedback grouped by issue, with attribution where available.",
    cy,
  );
  for (const [i, it] of result.issues.entries()) {
    if (!it.quotes?.length) continue;
    cy = ensureSpace(doc, cy + 2, 16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(20);
    doc.text(`${i + 1}. ${it.title}`, MARGIN, cy);
    cy += 5;
    for (const raw of it.quotes) {
      cy = ensureSpace(doc, cy, 14);
      const text = `“${quoteText(raw)}”`;
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(40);
      const lines = doc.splitTextToSize(text, CONTENT_WIDTH - 4);
      doc.text(lines, MARGIN + 4, cy);
      cy += lines.length * 4 + 1;
      const attr = quoteAttr(raw);
      if (attr) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(120);
        doc.text(`— ${attr}`, MARGIN + 4, cy);
        cy += 4;
      }
      cy += 1;
    }
    cy += 2;
  }

  doc.save(`${safeName(productName)}-analysis.pdf`);
}

export function exportRoadmapPdf(items: RoadmapItem[], productName: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" }) as jsPDF & {
    lastAutoTable?: { finalY: number };
  };
  header(doc, productName, "Roadmap");

  // Summary
  const counts = {
    P1: items.filter((i) => i.priority === "P1").length,
    P2: items.filter((i) => i.priority === "P2").length,
    P3: items.filter((i) => i.priority === "P3").length,
  };
  autoTable(doc, {
    startY: 36,
    head: [["Total items", "Priority mix (P1·P2·P3)", "Now bucket"]],
    body: [[
      String(items.length),
      `${counts.P1} · ${counts.P2} · ${counts.P3}`,
      String(items.filter((i) => i.bucket === "now").length),
    ]],
    theme: "grid",
    headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 10 },
    margin: { left: MARGIN, right: MARGIN },
  });

  let y = getY(doc);
  const buckets: Bucket[] = ["now", "next", "later"];
  for (const b of buckets) {
    const inBucket = items.filter((i) => i.bucket === b);
    if (!inBucket.length) continue;
    y = ensureSpace(doc, y + 2, 20);
    y = sectionTitle(doc, `${BUCKET_META[b].label} — ${BUCKET_META[b].subtitle}`, y);
    autoTable(doc, {
      startY: y,
      head: [["Title", "Quarter", "Priority", "Effort", "Impact", "Mentions"]],
      body: inBucket.map((it) => [
        it.title,
        formatQuarter(it.quarter),
        it.priority,
        it.effort,
        it.impactScore,
        it.mentions,
      ]),
      theme: "striped",
      headStyles: { fillColor: [30, 30, 30], textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = getY(doc);
  }

  // Comments appendix — every quote for every item
  doc.addPage();
  let cy = 20;
  cy = sectionTitle(doc, "Appendix — Comments & evidence", cy);
  cy = paragraph(
    doc,
    "Verbatim user feedback grouped by roadmap item, with attribution where available.",
    cy,
  );
  for (const it of items) {
    if (!it.quotes?.length && !it.rationale) continue;
    cy = ensureSpace(doc, cy + 2, 16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(20);
    doc.text(`${it.title} — ${formatQuarter(it.quarter)} · ${it.priority}`, MARGIN, cy);
    cy += 5;
    if (it.rationale) cy = paragraph(doc, it.rationale, cy);
    for (const raw of it.quotes ?? []) {
      cy = ensureSpace(doc, cy, 14);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(40);
      const lines = doc.splitTextToSize(`“${quoteText(raw)}”`, CONTENT_WIDTH - 4);
      doc.text(lines, MARGIN + 4, cy);
      cy += lines.length * 4 + 1;
      const attr = quoteAttr(raw);
      if (attr) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(120);
        doc.text(`— ${attr}`, MARGIN + 4, cy);
        cy += 4;
      }
      cy += 1;
    }
    cy += 2;
  }
  }

  doc.save(`${safeName(productName)}-roadmap.pdf`);
}
