import jsPDF from "jspdf";
import type { PRD } from "./prd";

const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297;
const MARGIN = 18;
const MARGIN_TOP = 20;
const MARGIN_BOTTOM = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const PAGE_BOTTOM = PAGE_HEIGHT - MARGIN_BOTTOM;

function safeName(s: string): string {
  return (s || "untitled").replace(/[^a-z0-9-_]+/gi, "-").toLowerCase();
}

function ensure(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_BOTTOM) {
    doc.addPage();
    return MARGIN_TOP;
  }
  return y;
}

interface WriteOpts {
  x?: number;
  size?: number;
  font?: "normal" | "bold" | "italic";
  lineHeight?: number;
  color?: number;
  hangingIndent?: number; // for bullets
}

function write(doc: jsPDF, text: string, y: number, opts: WriteOpts = {}): number {
  if (!text) return y;
  const x = opts.x ?? MARGIN;
  const size = opts.size ?? 10;
  const font = opts.font ?? "normal";
  const lh = opts.lineHeight ?? size * 0.45 + 1.5;
  const color = opts.color ?? 60;
  const width = CONTENT_WIDTH - (x - MARGIN);
  doc.setFont("helvetica", font);
  doc.setFontSize(size);
  doc.setTextColor(color);
  const lines = doc.splitTextToSize(text, width);
  for (const line of lines) {
    y = ensure(doc, y, lh);
    doc.text(line, x, y);
    y += lh;
  }
  return y;
}

function bullet(doc: jsPDF, marker: string, text: string, y: number): number {
  // Marker at MARGIN+2, text at MARGIN+8 with same width offset.
  const startY = ensure(doc, y, 5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text(marker, MARGIN + 2, startY);
  return write(doc, text, startY, { x: MARGIN + 8, size: 10 });
}

function h1(doc: jsPDF, text: string, y: number): number {
  y = ensure(doc, y + 2, 10);
  return write(doc, text, y, { size: 16, font: "bold", color: 20, lineHeight: 8 });
}

function h2(doc: jsPDF, text: string, y: number): number {
  y = ensure(doc, y + 4, 9);
  const after = write(doc, text, y, {
    size: 12,
    font: "bold",
    color: 20,
    lineHeight: 6.5,
  });
  doc.setDrawColor(220);
  doc.line(MARGIN, after - 4, PAGE_WIDTH - MARGIN, after - 4);
  return after + 1;
}

function h3(doc: jsPDF, text: string, y: number): number {
  y = ensure(doc, y + 2, 7);
  return write(doc, text, y, { size: 11, font: "bold", color: 30, lineHeight: 5.5 });
}

function sectionBreak(doc: jsPDF, y: number): number {
  // Start a new page if there's less than ~50mm of room left.
  if (y > PAGE_BOTTOM - 50) {
    doc.addPage();
    return MARGIN_TOP;
  }
  return y + 4;
}

export function exportPRDPdf(prd: PRD, productName: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // Title block
  let y = MARGIN_TOP;
  y = write(doc, prd.title || "Product Requirements Document", y, {
    size: 18,
    font: "bold",
    color: 20,
    lineHeight: 8,
  });
  y = write(
    doc,
    `${prd.version} · ${prd.status} · Generated by InsightFlow`,
    y,
    { size: 9, color: 120, lineHeight: 5 },
  );
  doc.setDrawColor(220);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 6;

  // Overview
  y = h2(doc, "Overview", y);
  y = write(doc, prd.overview, y);

  y = h2(doc, "Problem statement", y);
  y = write(doc, prd.problemStatement, y);

  y = h2(doc, "Goals", y);
  prd.goals.forEach((g, i) => {
    y = bullet(doc, `${i + 1}.`, g, y);
  });

  y = h2(doc, "Non-goals", y);
  prd.nonGoals.forEach((g) => {
    y = bullet(doc, "•", g, y);
  });

  // Epics
  y = sectionBreak(doc, y);
  y = h1(doc, "Epics & User Stories", y);
  for (const epic of prd.epics) {
    y = h2(doc, `${epic.id} — ${epic.title}`, y);
    y = write(doc, epic.description, y);
    y = write(doc, `Business value: ${epic.businessValue}`, y, {
      font: "italic",
      color: 80,
    });

    for (const s of epic.userStories) {
      y = h3(
        doc,
        `${s.id} — ${s.title}  [${s.priority} · Effort ${s.estimatedEffort}]`,
        y,
      );
      y = write(doc, s.story, y, { font: "italic", color: 60 });
      y = write(doc, "Acceptance criteria:", y, {
        size: 9,
        font: "bold",
        color: 40,
        lineHeight: 5,
      });
      for (const ac of s.acceptanceCriteria) {
        y = bullet(doc, "☐", ac, y);
      }
      if (s.designNotes) y = write(doc, `Design notes: ${s.designNotes}`, y, { x: MARGIN + 2 });
      if (s.devNotes) y = write(doc, `Dev notes: ${s.devNotes}`, y, { x: MARGIN + 2 });
      y += 2;
    }
  }

  // Execution
  y = sectionBreak(doc, y);
  y = h1(doc, "Execution Guide", y);
  for (const p of prd.executionGuide) {
    y = h2(doc, `${p.phase} — ${p.sprint}`, y);
    y = write(doc, `Focus: ${p.focus}`, y);
    if (p.tasks.length) {
      y = h3(doc, "Tasks", y);
      p.tasks.forEach((t) => (y = bullet(doc, "•", t, y)));
    }
    if (p.dependencies.length) {
      y = h3(doc, "Dependencies", y);
      p.dependencies.forEach((t) => (y = bullet(doc, "•", t, y)));
    }
    if (p.risks.length) {
      y = h3(doc, "Risks", y);
      p.risks.forEach((t) => (y = bullet(doc, "•", t, y)));
    }
    y = h3(doc, "PM Recommendation", y);
    y = write(doc, p.recommendedApproach, y, { x: MARGIN + 2 });
    y += 2;
  }

  // Metrics + open questions
  y = sectionBreak(doc, y);
  y = h1(doc, "Success Metrics & Open Questions", y);
  y = h2(doc, "Success metrics", y);
  prd.successMetrics.forEach((m, i) => {
    y = bullet(doc, `${i + 1}.`, m, y);
  });
  y = h2(doc, "Open questions", y);
  prd.openQuestions.forEach((q) => {
    y = bullet(doc, "•", `(Unresolved) ${q}`, y);
  });

  doc.save(`${safeName(productName)}-prd.pdf`);
}
