import jsPDF from "jspdf";
import type { PRD } from "./prd";

const MARGIN = 14;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function safeName(s: string): string {
  return (s || "untitled").replace(/[^a-z0-9-_]+/gi, "-").toLowerCase();
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 285) {
    doc.addPage();
    return 20;
  }
  return y;
}

function paragraph(doc: jsPDF, text: string, y: number, indent = 0): number {
  if (!text) return y;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH - indent);
  y = ensureSpace(doc, y, lines.length * 5);
  doc.text(lines, MARGIN + indent, y);
  return y + lines.length * 5 + 2;
}

function h1(doc: jsPDF, text: string, y: number): number {
  y = ensureSpace(doc, y, 12);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(20);
  doc.text(text, MARGIN, y);
  return y + 8;
}

function h2(doc: jsPDF, text: string, y: number): number {
  y = ensureSpace(doc, y + 4, 10);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(20);
  doc.text(text, MARGIN, y);
  doc.setDrawColor(220);
  doc.line(MARGIN, y + 1.5, PAGE_WIDTH - MARGIN, y + 1.5);
  return y + 6;
}

function h3(doc: jsPDF, text: string, y: number): number {
  y = ensureSpace(doc, y + 2, 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30);
  doc.text(text, MARGIN, y);
  return y + 5;
}

export function exportPRDPdf(prd: PRD, productName: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // Title page header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20);
  doc.text(prd.title || "Product Requirements Document", MARGIN, 22);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    `${prd.version} · ${prd.status} · Generated by InsightFlow`,
    MARGIN,
    28,
  );
  doc.setDrawColor(220);
  doc.line(MARGIN, 32, PAGE_WIDTH - MARGIN, 32);

  let y = 40;

  // Overview
  y = h2(doc, "Overview", y);
  y = paragraph(doc, prd.overview, y);
  y = h2(doc, "Problem statement", y);
  y = paragraph(doc, prd.problemStatement, y);

  y = h2(doc, "Goals", y);
  prd.goals.forEach((g, i) => {
    y = paragraph(doc, `${i + 1}. ${g}`, y);
  });

  y = h2(doc, "Non-goals", y);
  prd.nonGoals.forEach((g) => {
    y = paragraph(doc, `• ${g}`, y);
  });

  // Epics
  doc.addPage();
  y = 20;
  y = h1(doc, "Epics & User Stories", y);
  for (const epic of prd.epics) {
    y = h2(doc, `${epic.id} — ${epic.title}`, y);
    y = paragraph(doc, epic.description, y);
    y = paragraph(doc, `Business value: ${epic.businessValue}`, y);

    for (const s of epic.userStories) {
      y = h3(doc, `${s.id} — ${s.title}  [${s.priority} · Effort ${s.estimatedEffort}]`, y);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(60);
      const storyLines = doc.splitTextToSize(s.story, CONTENT_WIDTH - 4);
      y = ensureSpace(doc, y, storyLines.length * 5);
      doc.text(storyLines, MARGIN + 4, y);
      y += storyLines.length * 5 + 2;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(40);
      y = ensureSpace(doc, y, 6);
      doc.text("Acceptance criteria:", MARGIN + 4, y);
      y += 4;
      for (const ac of s.acceptanceCriteria) {
        y = paragraph(doc, `☐ ${ac}`, y, 8);
      }
      if (s.designNotes) y = paragraph(doc, `Design notes: ${s.designNotes}`, y, 4);
      if (s.devNotes) y = paragraph(doc, `Dev notes: ${s.devNotes}`, y, 4);
      y += 2;
    }
  }

  // Execution guide
  doc.addPage();
  y = 20;
  y = h1(doc, "Execution Guide", y);
  for (const p of prd.executionGuide) {
    y = h2(doc, `${p.phase} — ${p.sprint}`, y);
    y = paragraph(doc, `Focus: ${p.focus}`, y);
    if (p.tasks.length) {
      y = h3(doc, "Tasks", y);
      p.tasks.forEach((t) => (y = paragraph(doc, `• ${t}`, y, 4)));
    }
    if (p.dependencies.length) {
      y = h3(doc, "Dependencies", y);
      p.dependencies.forEach((t) => (y = paragraph(doc, `• ${t}`, y, 4)));
    }
    if (p.risks.length) {
      y = h3(doc, "Risks", y);
      p.risks.forEach((t) => (y = paragraph(doc, `• ${t}`, y, 4)));
    }
    y = h3(doc, "PM Recommendation", y);
    y = paragraph(doc, p.recommendedApproach, y, 4);
    y += 2;
  }

  // Metrics + open questions
  doc.addPage();
  y = 20;
  y = h1(doc, "Success Metrics & Open Questions", y);
  y = h2(doc, "Success metrics", y);
  prd.successMetrics.forEach((m, i) => {
    y = paragraph(doc, `${i + 1}. ${m}`, y);
  });
  y = h2(doc, "Open questions", y);
  prd.openQuestions.forEach((q) => {
    y = paragraph(doc, `• (Unresolved) ${q}`, y);
  });

  doc.save(`${safeName(productName)}-prd.pdf`);
}
